### ISSUE TITLE
On "constant time"

### ISSUE THREAD

**Issue by dot-asm** [paulmillr/noble-bls12-381#56]
Quoting README.md:

> But, JIT-compiler and Garbage Collector make "constant time" extremely hard to achieve in a scripting language.

In the context of cryptographic security "constant time"  is not about elapsed wall-clock time it takes to perform an operation, but its **invariance** in relation to secret material. In other words it's not like there may be no timing variations whatsoever, but whatever variations there are, they may not depend on the secret **value**. And as long as this condition is met, JIT or Garbage Collector may intervene at **any** time, including during secret-key operations, and for as long as deemed necessary.

I'm not asserting that achieving constant-time-ness in pure JavaScript is feasible, but JIT or Garbage Collector are not as large of obstacles as suggested. In JavaScript or elsewhere.

**Comment by paulmillr** [comment]
Constant-time operations is a battle between developer and compiler. Developer wants slow but constant time code, compiler aims to produce the fastest possible code.

With JIT we don't have any control over what code will run, since JIT can easily optimize away
constant-time operations. Or, JIT can use any machine instruction / code which will have timing variation depending on secret value.

For compiled languages we can verify compiler output and make sure that code is actually 
constant-time. BTW, this is very hard: even memory access patterns can easily make code non-constant time because of CPU caches.

For JS there is no such option. Suppose you wrote constant-time code and verified that it is indeed CT within all JS engines with all use-cases. It can easily change with next update of browser/JS engine. WASM can use JIT too.

As for GC: it makes timing attacks harder. On the other hand, it can expose some information about secret value: it will be very hard to restore the secret from it. At the same time, restoring secret values from bigint operation in EC is hard too.

So, how bad it actually is for JS? If you expose any api that depends on privateKey, 
like uncached access to getPublicKey or you're creating signature with enough speed to uncover timing variances, there can be a problem.

However, just caching getPublicKey (for example at start of application) or asking user confirmation for transaction signing (in web wallets) could make it safe enough.

**Comment by dot-asm** [comment]
> Constant-time operations is a battle between developer and compiler.

Correct. And my point is that JIT and Garbage Collection are not a part of the equation. Because the struggle is the same in either case. It's not JIT or GC that makes pure JS [or something else!] unsuitable as a secure platform. 

As for "something else" in the previous paragraph. Speaking of Webasm. Question is not whether or not it JITs, or when JS makes a call, or even how long it takes each time. [Again, it's not about wall-clock time.] Question is if there is a contract that VM is supposed to uphold that facilitates constant-time execution. Well, this doesn't resolve the conflict between developer and high-level language compiler, but that's not the current point.

As for "a contract to uphold." Well, I'm not that much into Wasm spirit, but spec does talk about instruction execution determinism. Which suggests that VM is obliged to execute instructions in provided order and is not free to perform certain optimizations. Most notably those that would reorder or omit loads and stores. And judging from what I've observed so far it is the case. Customarily this would do. Not saying that it actually does though, or that it will in perpetuity.
